# Generated by Django 2.0.7 on 2018-07-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
