# Generated by Django 2.0.4 on 2018-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0007_auto_20180730_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaobject',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=355),
        ),
    ]
