# Generated by Django 2.0.7 on 2018-07-11 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmanager', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], null=True, size=None),
        ),
    ]
